import type { Metadata } from "next";
import { Manrope, Outfit } from "next/font/google";
import SmoothScroll from "@/components/scroll/SmoothScroll";
import "./globals.css";
import Footer from "@/components/Footer";
import Navber from "@/components/Navber";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${manrope.variable} ${outfit.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-manrope">
        <Navber />
        <SmoothScroll>
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
